sudo: false

language: go

go:
  - 1.5.4
  - 1.6.2

env:
  global:
  - GO15VENDOREXPERIMENT='1'

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/kardianos/govendor
  - govendor sync

script:
  - go test -v -race -covermode=count -coverprofile=coverage.out ./
  - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_REPO_TOKEN"

before_deploy:
  - cd cmd/goexec
  - GOOS=linux GOARCH=amd64 go build -o goexec_linux_amd64
  - GOOS=darwin GOARCH=amd64 go build -o goexec_darwin_amd64

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 5Hc2R2hLP+aiTZF3zQGss//qdWoyevr/XFrNBfBv/Wj+WcOAtXPmY/MqAzt9Z8hV6BlWwXbGCNSGD57zjIQoXPlVZhmu+bEi1CaQ4pH5av3m4VBhOPZAaTIO9OWJuzxCGNwqQjrQnEJzWPt56ew81U1t1TjN0yXLaXB8wnvZcZ17BUkWGmp8FrOw3DkKwaS/lbaiAhF+3D/Nea0PDeWtDOIUoOTvXdMp8CSs+qpozGJRpvlD1LWFmQtMLvzVJ82h7RMn7ajeHVfX7FXrrgWl2gnsZ3MS3ivF8vvyggbOJdxl9zvlAUzkBwOAubcQCdOqMoXMZtATYiM3KEoCX6oCZtYtg+CM0EcvKaYz3DW4jIlTJ+e5fx10nYaEin/q+ryiZY61F8Pf1zthT+Pzu4Ew/aOCfxHq0wTDNs0PSE3F+VfbaU9P4Ei8DpamcV5QQFDQ3QHKpKBnXkifA5aMNScirUMD4/6T2/zpTxOsUUXjRA87W51uf7alr84k255XQNEy7L95toMTKmOSlY+aVs5CQjKtPKUcFWrtP2SDfi8v0aqxUEq4Lt3j1eC0NyTKhQjPAFCrkeDkRuqN2RwN6l8KFoMt7/kkHidV6YzQ0ZibKPeK3phJ6LlmV3E9OD1x87/KsL3KSNBtPJE+bhqhPQ1MSrAirL6uL32tEyhEJs3X5Lc=
  file:
  - goexec_linux_amd64
  - goexec_darwin_amd64
  on:
    tags: true

notifications:
  slack:
    secure: OQT4M7Kcv5mPsCD5nGZGjmjkLjiosBtBOWZOxOIcjAUNQfifsv9EwZkdQ6vDGmsLSgsTdMCsq1vAieOHv3erPV6x0VNkyZqZLFjMwNL3wOh/nYblBnfS/z/hER7H9bYpqKAuoNCPv/GLHtZqQUwtdtL/JHqklUvsAdUmM1H0z6GEheCnpY2idCix8sNOzrOc0H4URvTxnZ0UjJi3/oYq8oOlUW/RFoPWZY0TvIcWqsWRYO7OdgjmZakCtGd/QcwkQNheKXi90wlCTcZZsAU03YSBFO1h10NzwRcI+dKRxG+tk/mgrcaX2t8SCCIatHTNTYHLLZDrynbnVkzU0GZ8GUMxxA8crnZ+rqMnxcOwF48jg7d7JCYNkhNIN7s75CD/HnqO6NRqUS02AHNmbuhaSj2N6ZPAWAQf2PF7c3ZtZh+MyqLegcIBqZL+aofA0RgFZRbCmjiQP2wq/+euUzoxKE+aEmrBhX0AUmAGbCJXNA5sUbA5/no3znHSh2GcxTc6UysG2U6YGMLABkFyaPGbhrF9YK8o1/HTH1VGcl1jMSeIylsKXq0hOygRm6+dRwFv/A6t5X1i/h0O1oYFa/8pMs3RNBOJNQynDuAf0e96sKoax7ZRKaT8sSIei62pEn4MMnPAMEkpc4KPdPJctwS3ZJWAM2bKL+D7sHEGVgkW914=
